#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 154
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 24
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define PRODUCTION_ID_COUNT 40

enum ts_symbol_identifiers {
  sym_identity = 1,
  sym_comment = 2,
  anon_sym_include = 3,
  anon_sym_category = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_abstract = 7,
  anon_sym_asset = 8,
  anon_sym_extends = 9,
  anon_sym_PIPE = 10,
  anon_sym_AMP = 11,
  anon_sym_POUND = 12,
  anon_sym_E = 13,
  anon_sym_BANGE = 14,
  anon_sym_AT = 15,
  anon_sym_COMMA = 16,
  anon_sym_LBRACK = 17,
  anon_sym_RBRACK = 18,
  anon_sym_LPAREN = 19,
  anon_sym_RPAREN = 20,
  anon_sym_PLUS = 21,
  anon_sym_DASH = 22,
  anon_sym_STAR = 23,
  anon_sym_SLASH = 24,
  anon_sym_CARET = 25,
  anon_sym_COLON = 26,
  anon_sym_associations = 27,
  anon_sym_LT_DASH_DASH = 28,
  anon_sym_DASH_DASH_GT = 29,
  anon_sym_DOT_DOT = 30,
  anon_sym_info = 31,
  sym_string = 32,
  sym_integer = 33,
  sym_cia = 34,
  sym_source_file = 35,
  sym_declaration = 36,
  sym_include_declaration = 37,
  sym_category_declaration = 38,
  sym_asset = 39,
  sym_attack_step = 40,
  sym__ttc = 41,
  sym__ttc_parenthesized = 42,
  sym_ttc_primary = 43,
  sym_ttc_distribution = 44,
  sym_ttc_binop = 45,
  sym_define_declaration = 46,
  sym_associations_declaration = 47,
  sym_association = 48,
  sym_multiplicity = 49,
  sym__multiplicity_atom = 50,
  sym_multiplicity_range = 51,
  sym_meta = 52,
  sym_star = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_category_declaration_repeat1 = 55,
  aux_sym_category_declaration_repeat2 = 56,
  aux_sym_asset_repeat1 = 57,
  aux_sym_attack_step_repeat1 = 58,
  aux_sym_ttc_distribution_repeat1 = 59,
  aux_sym_associations_declaration_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identity] = "identity",
  [sym_comment] = "comment",
  [anon_sym_include] = "include",
  [anon_sym_category] = "category",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_abstract] = "abstract",
  [anon_sym_asset] = "asset",
  [anon_sym_extends] = "extends",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_POUND] = "#",
  [anon_sym_E] = "E",
  [anon_sym_BANGE] = "!E",
  [anon_sym_AT] = "@",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_CARET] = "^",
  [anon_sym_COLON] = ":",
  [anon_sym_associations] = "associations",
  [anon_sym_LT_DASH_DASH] = "<--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_info] = "info",
  [sym_string] = "string",
  [sym_integer] = "integer",
  [sym_cia] = "cia",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_include_declaration] = "include_declaration",
  [sym_category_declaration] = "category_declaration",
  [sym_asset] = "asset",
  [sym_attack_step] = "attack_step",
  [sym__ttc] = "_ttc",
  [sym__ttc_parenthesized] = "_ttc_parenthesized",
  [sym_ttc_primary] = "ttc_primary",
  [sym_ttc_distribution] = "ttc_distribution",
  [sym_ttc_binop] = "ttc_binop",
  [sym_define_declaration] = "define_declaration",
  [sym_associations_declaration] = "associations_declaration",
  [sym_association] = "association",
  [sym_multiplicity] = "multiplicity",
  [sym__multiplicity_atom] = "_multiplicity_atom",
  [sym_multiplicity_range] = "multiplicity_range",
  [sym_meta] = "meta",
  [sym_star] = "star",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_category_declaration_repeat1] = "category_declaration_repeat1",
  [aux_sym_category_declaration_repeat2] = "category_declaration_repeat2",
  [aux_sym_asset_repeat1] = "asset_repeat1",
  [aux_sym_attack_step_repeat1] = "attack_step_repeat1",
  [aux_sym_ttc_distribution_repeat1] = "ttc_distribution_repeat1",
  [aux_sym_associations_declaration_repeat1] = "associations_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identity] = sym_identity,
  [sym_comment] = sym_comment,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_category] = anon_sym_category,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_asset] = anon_sym_asset,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_BANGE] = anon_sym_BANGE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_associations] = anon_sym_associations,
  [anon_sym_LT_DASH_DASH] = anon_sym_LT_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_info] = anon_sym_info,
  [sym_string] = sym_string,
  [sym_integer] = sym_integer,
  [sym_cia] = sym_cia,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_include_declaration] = sym_include_declaration,
  [sym_category_declaration] = sym_category_declaration,
  [sym_asset] = sym_asset,
  [sym_attack_step] = sym_attack_step,
  [sym__ttc] = sym__ttc,
  [sym__ttc_parenthesized] = sym__ttc_parenthesized,
  [sym_ttc_primary] = sym_ttc_primary,
  [sym_ttc_distribution] = sym_ttc_distribution,
  [sym_ttc_binop] = sym_ttc_binop,
  [sym_define_declaration] = sym_define_declaration,
  [sym_associations_declaration] = sym_associations_declaration,
  [sym_association] = sym_association,
  [sym_multiplicity] = sym_multiplicity,
  [sym__multiplicity_atom] = sym__multiplicity_atom,
  [sym_multiplicity_range] = sym_multiplicity_range,
  [sym_meta] = sym_meta,
  [sym_star] = sym_star,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_category_declaration_repeat1] = aux_sym_category_declaration_repeat1,
  [aux_sym_category_declaration_repeat2] = aux_sym_category_declaration_repeat2,
  [aux_sym_asset_repeat1] = aux_sym_asset_repeat1,
  [aux_sym_attack_step_repeat1] = aux_sym_attack_step_repeat1,
  [aux_sym_ttc_distribution_repeat1] = aux_sym_ttc_distribution_repeat1,
  [aux_sym_associations_declaration_repeat1] = aux_sym_associations_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identity] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_category] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_asset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANGE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_associations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_cia] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_include_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_category_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_asset] = {
    .visible = true,
    .named = true,
  },
  [sym_attack_step] = {
    .visible = true,
    .named = true,
  },
  [sym__ttc] = {
    .visible = false,
    .named = true,
  },
  [sym__ttc_parenthesized] = {
    .visible = false,
    .named = true,
  },
  [sym_ttc_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_ttc_distribution] = {
    .visible = true,
    .named = true,
  },
  [sym_ttc_binop] = {
    .visible = true,
    .named = true,
  },
  [sym_define_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_associations_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_association] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicity] = {
    .visible = true,
    .named = true,
  },
  [sym__multiplicity_atom] = {
    .visible = false,
    .named = true,
  },
  [sym_multiplicity_range] = {
    .visible = true,
    .named = true,
  },
  [sym_meta] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_category_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_category_declaration_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_asset_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attack_step_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ttc_distribution_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_associations_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assets = 1,
  field_body = 2,
  field_cias = 3,
  field_end = 4,
  field_extends = 5,
  field_file = 6,
  field_id = 7,
  field_info = 8,
  field_left = 9,
  field_left_field_id = 10,
  field_left_id = 11,
  field_left_mult = 12,
  field_meta = 13,
  field_operator = 14,
  field_right = 15,
  field_right_field_id = 16,
  field_right_id = 17,
  field_right_mult = 18,
  field_start = 19,
  field_step_type = 20,
  field_tag = 21,
  field_ttc = 22,
  field_value = 23,
  field_values = 24,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assets] = "assets",
  [field_body] = "body",
  [field_cias] = "cias",
  [field_end] = "end",
  [field_extends] = "extends",
  [field_file] = "file",
  [field_id] = "id",
  [field_info] = "info",
  [field_left] = "left",
  [field_left_field_id] = "left_field_id",
  [field_left_id] = "left_id",
  [field_left_mult] = "left_mult",
  [field_meta] = "meta",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_right_field_id] = "right_field_id",
  [field_right_id] = "right_id",
  [field_right_mult] = "right_mult",
  [field_start] = "start",
  [field_step_type] = "step_type",
  [field_tag] = "tag",
  [field_ttc] = "ttc",
  [field_value] = "value",
  [field_values] = "values",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 1},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 3},
  [14] = {.index = 25, .length = 3},
  [15] = {.index = 28, .length = 2},
  [16] = {.index = 30, .length = 3},
  [17] = {.index = 33, .length = 3},
  [18] = {.index = 36, .length = 4},
  [19] = {.index = 40, .length = 4},
  [20] = {.index = 44, .length = 4},
  [21] = {.index = 48, .length = 4},
  [22] = {.index = 52, .length = 4},
  [23] = {.index = 56, .length = 5},
  [24] = {.index = 61, .length = 3},
  [25] = {.index = 64, .length = 5},
  [26] = {.index = 69, .length = 5},
  [27] = {.index = 74, .length = 6},
  [28] = {.index = 80, .length = 3},
  [29] = {.index = 83, .length = 7},
  [30] = {.index = 90, .length = 5},
  [31] = {.index = 95, .length = 2},
  [32] = {.index = 97, .length = 6},
  [33] = {.index = 103, .length = 8},
  [34] = {.index = 111, .length = 3},
  [35] = {.index = 114, .length = 7},
  [36] = {.index = 121, .length = 7},
  [37] = {.index = 128, .length = 8},
  [38] = {.index = 136, .length = 8},
  [39] = {.index = 144, .length = 9},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_file, 1},
  [1] =
    {field_id, 1},
  [2] =
    {field_id, 1},
    {field_value, 3},
  [4] =
    {field_assets, 3},
    {field_id, 1},
  [6] =
    {field_id, 1},
    {field_meta, 2},
  [8] =
    {field_id, 0},
    {field_info, 3},
  [10] =
    {field_assets, 4},
    {field_id, 1},
    {field_meta, 2},
  [13] =
    {field_id, 2},
  [14] =
    {field_id, 1},
    {field_step_type, 0},
  [16] =
    {field_body, 3},
    {field_id, 1},
  [18] =
    {field_body, 4},
    {field_id, 2},
  [20] =
    {field_id, 2},
    {field_meta, 3},
  [22] =
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
  [25] =
    {field_body, 4},
    {field_id, 1},
    {field_meta, 2},
  [28] =
    {field_end, 2},
    {field_start, 0},
  [30] =
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
  [33] =
    {field_body, 5},
    {field_id, 2},
    {field_meta, 3},
  [36] =
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
  [40] =
    {field_body, 5},
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
  [44] =
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
    {field_meta, 4},
  [48] =
    {field_body, 6},
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
  [52] =
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
    {field_meta, 5},
  [56] =
    {field_cias, 2},
    {field_cias, 3},
    {field_cias, 4},
    {field_id, 1},
    {field_step_type, 0},
  [61] =
    {field_id, 1},
    {field_step_type, 0},
    {field_ttc, 3},
  [64] =
    {field_body, 6},
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
    {field_meta, 4},
  [69] =
    {field_body, 7},
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
    {field_meta, 5},
  [74] =
    {field_cias, 2},
    {field_cias, 3},
    {field_cias, 4},
    {field_cias, 5},
    {field_id, 1},
    {field_step_type, 0},
  [80] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [83] =
    {field_cias, 4},
    {field_cias, 5},
    {field_cias, 6},
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
  [90] =
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
    {field_ttc, 5},
  [95] =
    {field_id, 0},
    {field_values, 2},
  [97] =
    {field_cias, 2},
    {field_cias, 3},
    {field_cias, 4},
    {field_id, 1},
    {field_step_type, 0},
    {field_ttc, 6},
  [103] =
    {field_cias, 4},
    {field_cias, 5},
    {field_cias, 6},
    {field_cias, 7},
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
  [111] =
    {field_id, 0},
    {field_values, 2},
    {field_values, 3},
  [114] =
    {field_cias, 2},
    {field_cias, 3},
    {field_cias, 4},
    {field_cias, 5},
    {field_id, 1},
    {field_step_type, 0},
    {field_ttc, 7},
  [121] =
    {field_id, 6},
    {field_left_field_id, 2},
    {field_left_id, 0},
    {field_left_mult, 4},
    {field_right_field_id, 10},
    {field_right_id, 12},
    {field_right_mult, 8},
  [128] =
    {field_cias, 4},
    {field_cias, 5},
    {field_cias, 6},
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
    {field_ttc, 8},
  [136] =
    {field_id, 6},
    {field_left_field_id, 2},
    {field_left_id, 0},
    {field_left_mult, 4},
    {field_meta, 13},
    {field_right_field_id, 10},
    {field_right_id, 12},
    {field_right_mult, 8},
  [144] =
    {field_cias, 4},
    {field_cias, 5},
    {field_cias, 6},
    {field_cias, 7},
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
    {field_ttc, 9},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '!', 13,
        '"', 1,
        '#', 22,
        '&', 21,
        '(', 28,
        ')', 29,
        '*', 33,
        '+', 30,
        ',', 25,
        '-', 32,
        '.', 10,
        '/', 34,
        ':', 36,
        '<', 9,
        '@', 24,
        '[', 26,
        ']', 27,
        '^', 35,
        '{', 18,
        '|', 20,
        '}', 19,
        'A', 43,
        'C', 43,
        'I', 43,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'A' ||
          lookahead == 'C' ||
          lookahead == 'I') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '!', 13,
        '#', 22,
        '&', 21,
        '(', 28,
        ')', 29,
        '*', 33,
        '+', 30,
        '-', 31,
        '/', 34,
        '@', 24,
        '[', 26,
        ']', 27,
        '^', 35,
        '{', 18,
        '|', 20,
        '}', 19,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANGE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_DASH_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identity);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_cia);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'E') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 2:
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'x') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_asset);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_category);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_associations);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 14},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 14},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 14},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 14},
  [44] = {.lex_state = 14},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 14},
  [47] = {.lex_state = 14},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 14},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 14},
  [53] = {.lex_state = 14},
  [54] = {.lex_state = 14},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 14},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 14},
  [61] = {.lex_state = 14},
  [62] = {.lex_state = 14},
  [63] = {.lex_state = 14},
  [64] = {.lex_state = 14},
  [65] = {.lex_state = 14},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 14},
  [69] = {.lex_state = 14},
  [70] = {.lex_state = 14},
  [71] = {.lex_state = 14},
  [72] = {.lex_state = 14},
  [73] = {.lex_state = 14},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 14},
  [76] = {.lex_state = 14},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 14},
  [79] = {.lex_state = 14},
  [80] = {.lex_state = 14},
  [81] = {.lex_state = 14},
  [82] = {.lex_state = 14},
  [83] = {.lex_state = 14},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 14},
  [86] = {.lex_state = 14},
  [87] = {.lex_state = 14},
  [88] = {.lex_state = 14},
  [89] = {.lex_state = 14},
  [90] = {.lex_state = 14},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 14},
  [94] = {.lex_state = 14},
  [95] = {.lex_state = 14},
  [96] = {.lex_state = 14},
  [97] = {.lex_state = 14},
  [98] = {.lex_state = 14},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 14},
  [101] = {.lex_state = 14},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 14},
  [104] = {.lex_state = 14},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 14},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 14},
  [110] = {.lex_state = 14},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 14},
  [114] = {.lex_state = 14},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 14},
  [117] = {.lex_state = 14},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 14},
  [123] = {.lex_state = 14},
  [124] = {.lex_state = 14},
  [125] = {.lex_state = 11},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 14},
  [128] = {.lex_state = 14},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 14},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 11},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 3},
  [140] = {.lex_state = 14},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 14},
  [143] = {.lex_state = 11},
  [144] = {.lex_state = 14},
  [145] = {.lex_state = 14},
  [146] = {.lex_state = 14},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 14},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 14},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 14},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identity] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_category] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_asset] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_BANGE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_associations] = ACTIONS(1),
    [anon_sym_LT_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_cia] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(152),
    [sym_declaration] = STATE(2),
    [sym_include_declaration] = STATE(63),
    [sym_category_declaration] = STATE(63),
    [sym_define_declaration] = STATE(63),
    [sym_associations_declaration] = STATE(63),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(7),
    [anon_sym_category] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_associations] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      anon_sym_category,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_associations,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(63), 4,
      sym_include_declaration,
      sym_category_declaration,
      sym_define_declaration,
      sym_associations_declaration,
  [29] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(22), 1,
      anon_sym_category,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(28), 1,
      anon_sym_associations,
    STATE(3), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(63), 4,
      sym_include_declaration,
      sym_category_declaration,
      sym_define_declaration,
      sym_associations_declaration,
  [58] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [79] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [97] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [115] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(13), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [133] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [151] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(55), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [169] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [187] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [205] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [223] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [241] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(47), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [263] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(22), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [299] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [317] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    STATE(23), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [353] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(50), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [375] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(82), 6,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [411] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [429] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(52), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [451] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(34), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [473] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(35), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [495] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(36), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [517] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(53), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [539] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(11), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [557] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(57), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [579] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(45), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [601] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(47), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [619] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      sym_identity,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      sym_integer,
    STATE(37), 1,
      sym_ttc_distribution,
    STATE(46), 4,
      sym__ttc,
      sym__ttc_parenthesized,
      sym_ttc_primary,
      sym_ttc_binop,
  [641] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(96), 4,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [660] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(96), 5,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(96), 5,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [694] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(82), 6,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [709] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(106), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [724] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_SLASH,
    ACTIONS(110), 6,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    ACTIONS(114), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [754] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_LBRACK,
    ACTIONS(118), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_SLASH,
    ACTIONS(122), 6,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_SLASH,
    ACTIONS(126), 6,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_CARET,
  [799] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_LBRACK,
    ACTIONS(130), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [814] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(134), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [834] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [854] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [874] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_STAR,
    ACTIONS(144), 1,
      sym_integer,
    STATE(119), 1,
      sym_multiplicity_range,
    STATE(136), 1,
      sym_multiplicity,
    STATE(102), 2,
      sym__multiplicity_atom,
      sym_star,
  [894] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_STAR,
    ACTIONS(144), 1,
      sym_integer,
    STATE(119), 1,
      sym_multiplicity_range,
    STATE(150), 1,
      sym_multiplicity,
    STATE(102), 2,
      sym__multiplicity_atom,
      sym_star,
  [914] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [946] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [966] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(152), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [998] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [1010] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [1022] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_CARET,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [1066] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_identity,
    ACTIONS(168), 1,
      anon_sym_LBRACE,
    ACTIONS(170), 1,
      anon_sym_extends,
    STATE(81), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1083] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_identity,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    ACTIONS(174), 1,
      anon_sym_extends,
    STATE(87), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1100] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(178), 1,
      anon_sym_abstract,
    ACTIONS(180), 1,
      anon_sym_asset,
    STATE(70), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1139] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_abstract,
    ACTIONS(180), 1,
      anon_sym_asset,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(73), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [1156] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_identity,
    ACTIONS(191), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1204] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    ACTIONS(201), 1,
      anon_sym_abstract,
    ACTIONS(204), 1,
      anon_sym_asset,
    STATE(70), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [1221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1243] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_abstract,
    ACTIONS(180), 1,
      anon_sym_asset,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(70), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [1260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1271] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_abstract,
    ACTIONS(180), 1,
      anon_sym_asset,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [1299] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    STATE(86), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1313] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
    STATE(85), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1327] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(225), 1,
      anon_sym_LBRACE,
    STATE(83), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1341] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identity,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(80), 2,
      sym_association,
      aux_sym_associations_declaration_repeat1,
  [1355] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1369] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_identity,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(89), 2,
      sym_association,
      aux_sym_associations_declaration_repeat1,
  [1383] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_STAR,
    ACTIONS(240), 1,
      sym_integer,
    STATE(121), 2,
      sym__multiplicity_atom,
      sym_star,
  [1411] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1425] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1439] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identity,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1453] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      sym_identity,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
    STATE(90), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1467] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_identity,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    STATE(80), 2,
      sym_association,
      aux_sym_associations_declaration_repeat1,
  [1481] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_identity,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(66), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [1495] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    STATE(105), 1,
      aux_sym_attack_step_repeat1,
  [1508] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      aux_sym_attack_step_repeat1,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1539] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1557] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 3,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
      anon_sym_DOT_DOT,
  [1584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_DOT_DOT,
    ACTIONS(284), 2,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1631] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(105), 1,
      aux_sym_attack_step_repeat1,
  [1644] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(297), 1,
      anon_sym_RBRACE,
    STATE(111), 1,
      aux_sym_attack_step_repeat1,
  [1657] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1666] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      aux_sym_ttc_distribution_repeat1,
  [1679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1697] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      aux_sym_attack_step_repeat1,
  [1710] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    STATE(115), 1,
      aux_sym_ttc_distribution_repeat1,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1741] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
    STATE(115), 1,
      aux_sym_ttc_distribution_repeat1,
  [1754] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identity,
  [1763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1780] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 2,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
  [1788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 2,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
  [1804] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      sym_identity,
  [1811] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      sym_identity,
  [1818] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_identity,
  [1825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_cia,
  [1832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      sym_string,
  [1839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_identity,
  [1846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_identity,
  [1853] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_COLON,
  [1860] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym_identity,
  [1867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_RBRACK,
  [1874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      sym_cia,
  [1881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      sym_string,
  [1888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym_integer,
  [1895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      sym_string,
  [1902] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      anon_sym_LBRACK,
  [1909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_RBRACK,
  [1916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_COLON,
  [1923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_DASH_DASH_GT,
  [1930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      sym_identity,
  [1937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      anon_sym_LBRACE,
  [1944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      sym_identity,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      sym_cia,
  [1958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      sym_identity,
  [1965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      sym_identity,
  [1972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      sym_identity,
  [1979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      sym_integer,
  [1986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      anon_sym_LBRACK,
  [1993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identity,
  [2000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      anon_sym_LT_DASH_DASH,
  [2007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      anon_sym_info,
  [2014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      ts_builtin_sym_end,
  [2021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      anon_sym_asset,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 79,
  [SMALL_STATE(6)] = 97,
  [SMALL_STATE(7)] = 115,
  [SMALL_STATE(8)] = 133,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 169,
  [SMALL_STATE(11)] = 187,
  [SMALL_STATE(12)] = 205,
  [SMALL_STATE(13)] = 223,
  [SMALL_STATE(14)] = 241,
  [SMALL_STATE(15)] = 263,
  [SMALL_STATE(16)] = 281,
  [SMALL_STATE(17)] = 299,
  [SMALL_STATE(18)] = 317,
  [SMALL_STATE(19)] = 335,
  [SMALL_STATE(20)] = 353,
  [SMALL_STATE(21)] = 375,
  [SMALL_STATE(22)] = 393,
  [SMALL_STATE(23)] = 411,
  [SMALL_STATE(24)] = 429,
  [SMALL_STATE(25)] = 451,
  [SMALL_STATE(26)] = 473,
  [SMALL_STATE(27)] = 495,
  [SMALL_STATE(28)] = 517,
  [SMALL_STATE(29)] = 539,
  [SMALL_STATE(30)] = 557,
  [SMALL_STATE(31)] = 579,
  [SMALL_STATE(32)] = 601,
  [SMALL_STATE(33)] = 619,
  [SMALL_STATE(34)] = 641,
  [SMALL_STATE(35)] = 660,
  [SMALL_STATE(36)] = 677,
  [SMALL_STATE(37)] = 694,
  [SMALL_STATE(38)] = 709,
  [SMALL_STATE(39)] = 724,
  [SMALL_STATE(40)] = 739,
  [SMALL_STATE(41)] = 754,
  [SMALL_STATE(42)] = 769,
  [SMALL_STATE(43)] = 784,
  [SMALL_STATE(44)] = 799,
  [SMALL_STATE(45)] = 814,
  [SMALL_STATE(46)] = 834,
  [SMALL_STATE(47)] = 854,
  [SMALL_STATE(48)] = 874,
  [SMALL_STATE(49)] = 894,
  [SMALL_STATE(50)] = 914,
  [SMALL_STATE(51)] = 934,
  [SMALL_STATE(52)] = 946,
  [SMALL_STATE(53)] = 966,
  [SMALL_STATE(54)] = 986,
  [SMALL_STATE(55)] = 998,
  [SMALL_STATE(56)] = 1010,
  [SMALL_STATE(57)] = 1022,
  [SMALL_STATE(58)] = 1042,
  [SMALL_STATE(59)] = 1054,
  [SMALL_STATE(60)] = 1066,
  [SMALL_STATE(61)] = 1083,
  [SMALL_STATE(62)] = 1100,
  [SMALL_STATE(63)] = 1117,
  [SMALL_STATE(64)] = 1128,
  [SMALL_STATE(65)] = 1139,
  [SMALL_STATE(66)] = 1156,
  [SMALL_STATE(67)] = 1171,
  [SMALL_STATE(68)] = 1182,
  [SMALL_STATE(69)] = 1193,
  [SMALL_STATE(70)] = 1204,
  [SMALL_STATE(71)] = 1221,
  [SMALL_STATE(72)] = 1232,
  [SMALL_STATE(73)] = 1243,
  [SMALL_STATE(74)] = 1260,
  [SMALL_STATE(75)] = 1271,
  [SMALL_STATE(76)] = 1288,
  [SMALL_STATE(77)] = 1299,
  [SMALL_STATE(78)] = 1313,
  [SMALL_STATE(79)] = 1327,
  [SMALL_STATE(80)] = 1341,
  [SMALL_STATE(81)] = 1355,
  [SMALL_STATE(82)] = 1369,
  [SMALL_STATE(83)] = 1383,
  [SMALL_STATE(84)] = 1397,
  [SMALL_STATE(85)] = 1411,
  [SMALL_STATE(86)] = 1425,
  [SMALL_STATE(87)] = 1439,
  [SMALL_STATE(88)] = 1453,
  [SMALL_STATE(89)] = 1467,
  [SMALL_STATE(90)] = 1481,
  [SMALL_STATE(91)] = 1495,
  [SMALL_STATE(92)] = 1508,
  [SMALL_STATE(93)] = 1521,
  [SMALL_STATE(94)] = 1530,
  [SMALL_STATE(95)] = 1539,
  [SMALL_STATE(96)] = 1548,
  [SMALL_STATE(97)] = 1557,
  [SMALL_STATE(98)] = 1566,
  [SMALL_STATE(99)] = 1575,
  [SMALL_STATE(100)] = 1584,
  [SMALL_STATE(101)] = 1593,
  [SMALL_STATE(102)] = 1602,
  [SMALL_STATE(103)] = 1613,
  [SMALL_STATE(104)] = 1622,
  [SMALL_STATE(105)] = 1631,
  [SMALL_STATE(106)] = 1644,
  [SMALL_STATE(107)] = 1657,
  [SMALL_STATE(108)] = 1666,
  [SMALL_STATE(109)] = 1679,
  [SMALL_STATE(110)] = 1688,
  [SMALL_STATE(111)] = 1697,
  [SMALL_STATE(112)] = 1710,
  [SMALL_STATE(113)] = 1723,
  [SMALL_STATE(114)] = 1732,
  [SMALL_STATE(115)] = 1741,
  [SMALL_STATE(116)] = 1754,
  [SMALL_STATE(117)] = 1763,
  [SMALL_STATE(118)] = 1772,
  [SMALL_STATE(119)] = 1780,
  [SMALL_STATE(120)] = 1788,
  [SMALL_STATE(121)] = 1796,
  [SMALL_STATE(122)] = 1804,
  [SMALL_STATE(123)] = 1811,
  [SMALL_STATE(124)] = 1818,
  [SMALL_STATE(125)] = 1825,
  [SMALL_STATE(126)] = 1832,
  [SMALL_STATE(127)] = 1839,
  [SMALL_STATE(128)] = 1846,
  [SMALL_STATE(129)] = 1853,
  [SMALL_STATE(130)] = 1860,
  [SMALL_STATE(131)] = 1867,
  [SMALL_STATE(132)] = 1874,
  [SMALL_STATE(133)] = 1881,
  [SMALL_STATE(134)] = 1888,
  [SMALL_STATE(135)] = 1895,
  [SMALL_STATE(136)] = 1902,
  [SMALL_STATE(137)] = 1909,
  [SMALL_STATE(138)] = 1916,
  [SMALL_STATE(139)] = 1923,
  [SMALL_STATE(140)] = 1930,
  [SMALL_STATE(141)] = 1937,
  [SMALL_STATE(142)] = 1944,
  [SMALL_STATE(143)] = 1951,
  [SMALL_STATE(144)] = 1958,
  [SMALL_STATE(145)] = 1965,
  [SMALL_STATE(146)] = 1972,
  [SMALL_STATE(147)] = 1979,
  [SMALL_STATE(148)] = 1986,
  [SMALL_STATE(149)] = 1993,
  [SMALL_STATE(150)] = 2000,
  [SMALL_STATE(151)] = 2007,
  [SMALL_STATE(152)] = 2014,
  [SMALL_STATE(153)] = 2021,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(144),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(140),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(141),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 2, 0, 9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 4, 0, 18),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_asset_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_asset_repeat1, 2, 0, 0), SHIFT_REPEAT(149),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ttc_primary, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ttc_primary, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ttc_binop, 3, 0, 28),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ttc_binop, 3, 0, 28),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 7, 0, 29),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ttc_distribution, 4, 0, 31),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ttc_distribution, 4, 0, 31),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 6, 0, 27),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 8, 0, 33),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ttc_distribution, 5, 0, 34),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ttc_distribution, 5, 0, 34),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ttc_parenthesized, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__ttc_parenthesized, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 5, 0, 23),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 5, 0, 24),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 7, 0, 30),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 11, 0, 39),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 8, 0, 32),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 9, 0, 35),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 10, 0, 37),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_declaration, 2, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(151),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_associations_declaration, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_declaration, 4, 0, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 5, 0, 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat2, 2, 0, 0),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(153),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(123),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 5, 0, 5),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_associations_declaration, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 6, 0, 7),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 4, 0, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_associations_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(148),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_associations_declaration_repeat1, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_association, 13, 0, 36), SHIFT(151),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_association, 13, 0, 36),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_association, 14, 0, 38), SHIFT(151),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_association, 14, 0, 38),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 5, 0, 10),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 19),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 20),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 8, 0, 21),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 8, 0, 22),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 4, 0, 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_star, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 5, 0, 5),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 11),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicity, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 8, 0, 25),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 9, 0, 26),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attack_step_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attack_step_repeat1, 2, 0, 0), SHIFT_REPEAT(132),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 12),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 5, 0, 8),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 13),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 14),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 16),
  [317] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ttc_distribution_repeat1, 2, 0, 0), SHIFT_REPEAT(134),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ttc_distribution_repeat1, 2, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta, 4, 0, 6),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 17),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicity_range, 3, 0, 15),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [388] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mal(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identity,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
