#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define PRODUCTION_ID_COUNT 31

enum ts_symbol_identifiers {
  sym_identity = 1,
  sym_comment = 2,
  anon_sym_include = 3,
  anon_sym_category = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_abstract = 7,
  anon_sym_asset = 8,
  anon_sym_extends = 9,
  anon_sym_PIPE = 10,
  anon_sym_AMP = 11,
  anon_sym_POUND = 12,
  anon_sym_E = 13,
  anon_sym_BANGE = 14,
  anon_sym_AT = 15,
  anon_sym_COMMA = 16,
  anon_sym_COLON = 17,
  anon_sym_associations = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  anon_sym_LT_DASH_DASH = 21,
  anon_sym_DASH_DASH_GT = 22,
  anon_sym_DOT_DOT = 23,
  anon_sym_info = 24,
  sym_string = 25,
  sym_integer = 26,
  sym_star = 27,
  sym_cia = 28,
  sym_source_file = 29,
  sym_declaration = 30,
  sym_include_declaration = 31,
  sym_category_declaration = 32,
  sym_asset = 33,
  sym_attack_step = 34,
  sym_define_declaration = 35,
  sym_associations_declaration = 36,
  sym_association = 37,
  sym_multiplicity = 38,
  sym__multiplicity_atom = 39,
  sym_multiplicity_range = 40,
  sym_meta = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_category_declaration_repeat1 = 43,
  aux_sym_category_declaration_repeat2 = 44,
  aux_sym_asset_repeat1 = 45,
  aux_sym_attack_step_repeat1 = 46,
  aux_sym_associations_declaration_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identity] = "identity",
  [sym_comment] = "comment",
  [anon_sym_include] = "include",
  [anon_sym_category] = "category",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_abstract] = "abstract",
  [anon_sym_asset] = "asset",
  [anon_sym_extends] = "extends",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_POUND] = "#",
  [anon_sym_E] = "E",
  [anon_sym_BANGE] = "!E",
  [anon_sym_AT] = "@",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_associations] = "associations",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT_DASH_DASH] = "<--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_info] = "info",
  [sym_string] = "string",
  [sym_integer] = "integer",
  [sym_star] = "star",
  [sym_cia] = "cia",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_include_declaration] = "include_declaration",
  [sym_category_declaration] = "category_declaration",
  [sym_asset] = "asset",
  [sym_attack_step] = "attack_step",
  [sym_define_declaration] = "define_declaration",
  [sym_associations_declaration] = "associations_declaration",
  [sym_association] = "association",
  [sym_multiplicity] = "multiplicity",
  [sym__multiplicity_atom] = "_multiplicity_atom",
  [sym_multiplicity_range] = "multiplicity_range",
  [sym_meta] = "meta",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_category_declaration_repeat1] = "category_declaration_repeat1",
  [aux_sym_category_declaration_repeat2] = "category_declaration_repeat2",
  [aux_sym_asset_repeat1] = "asset_repeat1",
  [aux_sym_attack_step_repeat1] = "attack_step_repeat1",
  [aux_sym_associations_declaration_repeat1] = "associations_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identity] = sym_identity,
  [sym_comment] = sym_comment,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_category] = anon_sym_category,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_abstract] = anon_sym_abstract,
  [anon_sym_asset] = anon_sym_asset,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_BANGE] = anon_sym_BANGE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_associations] = anon_sym_associations,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT_DASH_DASH] = anon_sym_LT_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_info] = anon_sym_info,
  [sym_string] = sym_string,
  [sym_integer] = sym_integer,
  [sym_star] = sym_star,
  [sym_cia] = sym_cia,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_include_declaration] = sym_include_declaration,
  [sym_category_declaration] = sym_category_declaration,
  [sym_asset] = sym_asset,
  [sym_attack_step] = sym_attack_step,
  [sym_define_declaration] = sym_define_declaration,
  [sym_associations_declaration] = sym_associations_declaration,
  [sym_association] = sym_association,
  [sym_multiplicity] = sym_multiplicity,
  [sym__multiplicity_atom] = sym__multiplicity_atom,
  [sym_multiplicity_range] = sym_multiplicity_range,
  [sym_meta] = sym_meta,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_category_declaration_repeat1] = aux_sym_category_declaration_repeat1,
  [aux_sym_category_declaration_repeat2] = aux_sym_category_declaration_repeat2,
  [aux_sym_asset_repeat1] = aux_sym_asset_repeat1,
  [aux_sym_attack_step_repeat1] = aux_sym_attack_step_repeat1,
  [aux_sym_associations_declaration_repeat1] = aux_sym_associations_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identity] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_category] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_abstract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_asset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANGE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_associations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [sym_cia] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_include_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_category_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_asset] = {
    .visible = true,
    .named = true,
  },
  [sym_attack_step] = {
    .visible = true,
    .named = true,
  },
  [sym_define_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_associations_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_association] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicity] = {
    .visible = true,
    .named = true,
  },
  [sym__multiplicity_atom] = {
    .visible = false,
    .named = true,
  },
  [sym_multiplicity_range] = {
    .visible = true,
    .named = true,
  },
  [sym_meta] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_category_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_category_declaration_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_asset_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attack_step_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_associations_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assets = 1,
  field_body = 2,
  field_cias = 3,
  field_end = 4,
  field_extends = 5,
  field_file = 6,
  field_id = 7,
  field_info = 8,
  field_left_field_id = 9,
  field_left_id = 10,
  field_left_mult = 11,
  field_meta = 12,
  field_right_field_id = 13,
  field_right_id = 14,
  field_right_mult = 15,
  field_start = 16,
  field_step_type = 17,
  field_tag = 18,
  field_value = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assets] = "assets",
  [field_body] = "body",
  [field_cias] = "cias",
  [field_end] = "end",
  [field_extends] = "extends",
  [field_file] = "file",
  [field_id] = "id",
  [field_info] = "info",
  [field_left_field_id] = "left_field_id",
  [field_left_id] = "left_id",
  [field_left_mult] = "left_mult",
  [field_meta] = "meta",
  [field_right_field_id] = "right_field_id",
  [field_right_id] = "right_id",
  [field_right_mult] = "right_mult",
  [field_start] = "start",
  [field_step_type] = "step_type",
  [field_tag] = "tag",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 1},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 3},
  [14] = {.index = 25, .length = 3},
  [15] = {.index = 28, .length = 2},
  [16] = {.index = 30, .length = 3},
  [17] = {.index = 33, .length = 3},
  [18] = {.index = 36, .length = 4},
  [19] = {.index = 40, .length = 4},
  [20] = {.index = 44, .length = 4},
  [21] = {.index = 48, .length = 4},
  [22] = {.index = 52, .length = 4},
  [23] = {.index = 56, .length = 5},
  [24] = {.index = 61, .length = 5},
  [25] = {.index = 66, .length = 5},
  [26] = {.index = 71, .length = 6},
  [27] = {.index = 77, .length = 7},
  [28] = {.index = 84, .length = 8},
  [29] = {.index = 92, .length = 7},
  [30] = {.index = 99, .length = 8},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_file, 1},
  [1] =
    {field_id, 1},
  [2] =
    {field_id, 1},
    {field_value, 3},
  [4] =
    {field_assets, 3},
    {field_id, 1},
  [6] =
    {field_id, 1},
    {field_meta, 2},
  [8] =
    {field_id, 0},
    {field_info, 3},
  [10] =
    {field_assets, 4},
    {field_id, 1},
    {field_meta, 2},
  [13] =
    {field_id, 2},
  [14] =
    {field_id, 1},
    {field_step_type, 0},
  [16] =
    {field_body, 3},
    {field_id, 1},
  [18] =
    {field_body, 4},
    {field_id, 2},
  [20] =
    {field_id, 2},
    {field_meta, 3},
  [22] =
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
  [25] =
    {field_body, 4},
    {field_id, 1},
    {field_meta, 2},
  [28] =
    {field_end, 2},
    {field_start, 0},
  [30] =
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
  [33] =
    {field_body, 5},
    {field_id, 2},
    {field_meta, 3},
  [36] =
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
  [40] =
    {field_body, 5},
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
  [44] =
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
    {field_meta, 4},
  [48] =
    {field_body, 6},
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
  [52] =
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
    {field_meta, 5},
  [56] =
    {field_cias, 2},
    {field_cias, 3},
    {field_cias, 4},
    {field_id, 1},
    {field_step_type, 0},
  [61] =
    {field_body, 6},
    {field_extends, 2},
    {field_extends, 3},
    {field_id, 1},
    {field_meta, 4},
  [66] =
    {field_body, 7},
    {field_extends, 3},
    {field_extends, 4},
    {field_id, 2},
    {field_meta, 5},
  [71] =
    {field_cias, 2},
    {field_cias, 3},
    {field_cias, 4},
    {field_cias, 5},
    {field_id, 1},
    {field_step_type, 0},
  [77] =
    {field_cias, 4},
    {field_cias, 5},
    {field_cias, 6},
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
  [84] =
    {field_cias, 4},
    {field_cias, 5},
    {field_cias, 6},
    {field_cias, 7},
    {field_id, 1},
    {field_step_type, 0},
    {field_tag, 2},
    {field_tag, 3},
  [92] =
    {field_id, 6},
    {field_left_field_id, 2},
    {field_left_id, 0},
    {field_left_mult, 4},
    {field_right_field_id, 10},
    {field_right_id, 12},
    {field_right_mult, 8},
  [99] =
    {field_id, 6},
    {field_left_field_id, 2},
    {field_left_id, 0},
    {field_left_mult, 4},
    {field_meta, 13},
    {field_right_field_id, 10},
    {field_right_id, 12},
    {field_right_mult, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '!', 12,
        '"', 1,
        '#', 21,
        '&', 20,
        '*', 36,
        ',', 24,
        '-', 7,
        '.', 10,
        '/', 4,
        ':', 25,
        '<', 9,
        '@', 23,
        '[', 26,
        ']', 27,
        '{', 17,
        '|', 19,
        '}', 18,
        'A', 35,
        'C', 35,
        'I', 35,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'A' ||
          lookahead == 'C' ||
          lookahead == 'I') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '!', 12,
        '#', 21,
        '&', 20,
        '/', 4,
        '@', 23,
        '{', 17,
        '|', 19,
        '}', 18,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANGE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_DASH_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identity);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_star);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_cia);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'E') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(2);
      if (lookahead == 'c') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 2:
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'x') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_asset);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_abstract);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_category);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_associations);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 13},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 13},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 13},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 13},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 13},
  [53] = {.lex_state = 13},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 13},
  [57] = {.lex_state = 13},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 13},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 13},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 13},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 13},
  [67] = {.lex_state = 13},
  [68] = {.lex_state = 13},
  [69] = {.lex_state = 13},
  [70] = {.lex_state = 13},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 13},
  [73] = {.lex_state = 13},
  [74] = {.lex_state = 13},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 13},
  [77] = {.lex_state = 13},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 13},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 13},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 13},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 13},
  [96] = {.lex_state = 13},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 13},
  [104] = {.lex_state = 13},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 13},
  [107] = {.lex_state = 13},
  [108] = {.lex_state = 13},
  [109] = {.lex_state = 13},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 13},
  [114] = {.lex_state = 13},
  [115] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identity] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_category] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_abstract] = ACTIONS(1),
    [anon_sym_asset] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_BANGE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_associations] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_star] = ACTIONS(1),
    [sym_cia] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(88),
    [sym_declaration] = STATE(2),
    [sym_include_declaration] = STATE(27),
    [sym_category_declaration] = STATE(27),
    [sym_define_declaration] = STATE(27),
    [sym_associations_declaration] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(7),
    [anon_sym_category] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_associations] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      anon_sym_category,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_associations,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(27), 4,
      sym_include_declaration,
      sym_category_declaration,
      sym_define_declaration,
      sym_associations_declaration,
  [29] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(22), 1,
      anon_sym_category,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(28), 1,
      anon_sym_associations,
    STATE(3), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(27), 4,
      sym_include_declaration,
      sym_category_declaration,
      sym_define_declaration,
      sym_associations_declaration,
  [58] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [76] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(13), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [94] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(7), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [112] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [130] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(16), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [148] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [166] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [184] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_AT,
    ACTIONS(49), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [202] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(55), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [220] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [238] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(18), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [274] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(20), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [310] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [328] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(21), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [346] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [364] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_attack_step,
      aux_sym_asset_repeat1,
    ACTIONS(33), 5,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [382] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 6,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_POUND,
      anon_sym_E,
      anon_sym_BANGE,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [467] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      anon_sym_abstract,
    ACTIONS(96), 1,
      anon_sym_asset,
    STATE(37), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [495] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_abstract,
    ACTIONS(96), 1,
      anon_sym_asset,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(40), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [523] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym_identity,
    ACTIONS(107), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [560] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(80), 1,
      sym__multiplicity_atom,
    STATE(85), 1,
      sym_multiplicity_range,
    STATE(105), 1,
      sym_multiplicity,
    ACTIONS(113), 2,
      sym_integer,
      sym_star,
  [577] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_abstract,
    ACTIONS(96), 1,
      anon_sym_asset,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(40), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [594] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identity,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_extends,
    STATE(53), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [622] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 1,
      anon_sym_abstract,
    ACTIONS(130), 1,
      anon_sym_asset,
    STATE(40), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_category,
      anon_sym_POUND,
      anon_sym_associations,
  [661] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      sym_identity,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_extends,
    STATE(50), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [678] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(80), 1,
      sym__multiplicity_atom,
    STATE(85), 1,
      sym_multiplicity_range,
    STATE(102), 1,
      sym_multiplicity,
    ACTIONS(113), 2,
      sym_integer,
      sym_star,
  [695] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_abstract,
    ACTIONS(96), 1,
      anon_sym_asset,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym_asset,
      aux_sym_category_declaration_repeat2,
  [712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [726] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
    STATE(52), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [740] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(149), 1,
      anon_sym_LBRACE,
    STATE(55), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [754] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_identity,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(51), 2,
      sym_association,
      aux_sym_associations_declaration_repeat1,
  [768] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [782] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_identity,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(54), 2,
      sym_association,
      aux_sym_associations_declaration_repeat1,
  [796] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [810] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [824] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_identity,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    STATE(54), 2,
      sym_association,
      aux_sym_associations_declaration_repeat1,
  [838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(168), 1,
      anon_sym_LBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [852] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identity,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    STATE(46), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_identity,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(58), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [880] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identity,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    STATE(33), 2,
      sym_meta,
      aux_sym_category_declaration_repeat1,
  [894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [921] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(83), 1,
      sym__multiplicity_atom,
    ACTIONS(188), 2,
      sym_integer,
      sym_star,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identity,
  [950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1013] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1031] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1040] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_attack_step_repeat1,
  [1053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1062] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_RBRACE,
      anon_sym_abstract,
      anon_sym_asset,
  [1071] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_attack_step_repeat1,
  [1084] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_attack_step_repeat1,
  [1097] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_DOT_DOT,
    ACTIONS(229), 2,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
  [1108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym_attack_step_repeat1,
  [1121] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_attack_step_repeat1,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
  [1142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 2,
      anon_sym_LBRACK,
      anon_sym_LT_DASH_DASH,
  [1158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_cia,
  [1165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identity,
  [1172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
  [1179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RBRACK,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identity,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_string,
  [1200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identity,
  [1207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_LBRACE,
  [1214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_COLON,
  [1221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_info,
  [1228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identity,
  [1235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
  [1242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_cia,
  [1249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym_string,
  [1256] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym_cia,
  [1263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identity,
  [1270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_LBRACK,
  [1277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_asset,
  [1284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identity,
  [1291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LT_DASH_DASH,
  [1298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_identity,
  [1305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identity,
  [1312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_identity,
  [1319] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_identity,
  [1326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_DASH_DASH_GT,
  [1333] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_RBRACK,
  [1340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_string,
  [1347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      sym_identity,
  [1354] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identity,
  [1361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 76,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 184,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 220,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 274,
  [SMALL_STATE(17)] = 292,
  [SMALL_STATE(18)] = 310,
  [SMALL_STATE(19)] = 328,
  [SMALL_STATE(20)] = 346,
  [SMALL_STATE(21)] = 364,
  [SMALL_STATE(22)] = 382,
  [SMALL_STATE(23)] = 397,
  [SMALL_STATE(24)] = 409,
  [SMALL_STATE(25)] = 421,
  [SMALL_STATE(26)] = 433,
  [SMALL_STATE(27)] = 445,
  [SMALL_STATE(28)] = 456,
  [SMALL_STATE(29)] = 467,
  [SMALL_STATE(30)] = 484,
  [SMALL_STATE(31)] = 495,
  [SMALL_STATE(32)] = 512,
  [SMALL_STATE(33)] = 523,
  [SMALL_STATE(34)] = 538,
  [SMALL_STATE(35)] = 549,
  [SMALL_STATE(36)] = 560,
  [SMALL_STATE(37)] = 577,
  [SMALL_STATE(38)] = 594,
  [SMALL_STATE(39)] = 611,
  [SMALL_STATE(40)] = 622,
  [SMALL_STATE(41)] = 639,
  [SMALL_STATE(42)] = 650,
  [SMALL_STATE(43)] = 661,
  [SMALL_STATE(44)] = 678,
  [SMALL_STATE(45)] = 695,
  [SMALL_STATE(46)] = 712,
  [SMALL_STATE(47)] = 726,
  [SMALL_STATE(48)] = 740,
  [SMALL_STATE(49)] = 754,
  [SMALL_STATE(50)] = 768,
  [SMALL_STATE(51)] = 782,
  [SMALL_STATE(52)] = 796,
  [SMALL_STATE(53)] = 810,
  [SMALL_STATE(54)] = 824,
  [SMALL_STATE(55)] = 838,
  [SMALL_STATE(56)] = 852,
  [SMALL_STATE(57)] = 866,
  [SMALL_STATE(58)] = 880,
  [SMALL_STATE(59)] = 894,
  [SMALL_STATE(60)] = 903,
  [SMALL_STATE(61)] = 912,
  [SMALL_STATE(62)] = 921,
  [SMALL_STATE(63)] = 932,
  [SMALL_STATE(64)] = 941,
  [SMALL_STATE(65)] = 950,
  [SMALL_STATE(66)] = 959,
  [SMALL_STATE(67)] = 968,
  [SMALL_STATE(68)] = 977,
  [SMALL_STATE(69)] = 986,
  [SMALL_STATE(70)] = 995,
  [SMALL_STATE(71)] = 1004,
  [SMALL_STATE(72)] = 1013,
  [SMALL_STATE(73)] = 1022,
  [SMALL_STATE(74)] = 1031,
  [SMALL_STATE(75)] = 1040,
  [SMALL_STATE(76)] = 1053,
  [SMALL_STATE(77)] = 1062,
  [SMALL_STATE(78)] = 1071,
  [SMALL_STATE(79)] = 1084,
  [SMALL_STATE(80)] = 1097,
  [SMALL_STATE(81)] = 1108,
  [SMALL_STATE(82)] = 1121,
  [SMALL_STATE(83)] = 1134,
  [SMALL_STATE(84)] = 1142,
  [SMALL_STATE(85)] = 1150,
  [SMALL_STATE(86)] = 1158,
  [SMALL_STATE(87)] = 1165,
  [SMALL_STATE(88)] = 1172,
  [SMALL_STATE(89)] = 1179,
  [SMALL_STATE(90)] = 1186,
  [SMALL_STATE(91)] = 1193,
  [SMALL_STATE(92)] = 1200,
  [SMALL_STATE(93)] = 1207,
  [SMALL_STATE(94)] = 1214,
  [SMALL_STATE(95)] = 1221,
  [SMALL_STATE(96)] = 1228,
  [SMALL_STATE(97)] = 1235,
  [SMALL_STATE(98)] = 1242,
  [SMALL_STATE(99)] = 1249,
  [SMALL_STATE(100)] = 1256,
  [SMALL_STATE(101)] = 1263,
  [SMALL_STATE(102)] = 1270,
  [SMALL_STATE(103)] = 1277,
  [SMALL_STATE(104)] = 1284,
  [SMALL_STATE(105)] = 1291,
  [SMALL_STATE(106)] = 1298,
  [SMALL_STATE(107)] = 1305,
  [SMALL_STATE(108)] = 1312,
  [SMALL_STATE(109)] = 1319,
  [SMALL_STATE(110)] = 1326,
  [SMALL_STATE(111)] = 1333,
  [SMALL_STATE(112)] = 1340,
  [SMALL_STATE(113)] = 1347,
  [SMALL_STATE(114)] = 1354,
  [SMALL_STATE(115)] = 1361,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 2, 0, 9),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_asset_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_asset_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 4, 0, 18),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 8, 0, 28),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 5, 0, 23),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 6, 0, 26),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attack_step, 7, 0, 27),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_declaration, 2, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 4, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_associations_declaration, 3, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_declaration, 4, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_associations_declaration, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 5, 0, 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat2, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(103),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_category_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(114),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 5, 0, 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_category_declaration, 6, 0, 7),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_associations_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_associations_declaration_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_association, 13, 0, 29), SHIFT(95),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_association, 13, 0, 29),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_association, 14, 0, 30), SHIFT(95),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_association, 14, 0, 30),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 5, 0, 10),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 5, 0, 8),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 5, 0, 5),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta, 4, 0, 6),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 12),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 13),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 6, 0, 14),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 16),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 17),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 4, 0, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 19),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 7, 0, 20),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 8, 0, 21),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 8, 0, 22),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 8, 0, 24),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asset, 9, 0, 25),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attack_step_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attack_step_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicity, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicity_range, 3, 0, 15),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [243] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mal(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identity,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
