name: Tree Sitter Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tree-sitter-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: tree-sitter/setup-action@v2
        with:
          tree-sitter-ref: 'v0.25.3'

      - name: Cache parser build
        id: cache-parser-build
        env:
          cache-name: cache-generated-parser
        uses: actions/cache@v4
        with:
          path: |
            ./src
            ./mal.so
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('grammar.js') }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ env.cache-name }}-
            ${{ matrix.os }}-build-

      - if: ${{ steps.cache-parser-build.outputs.cache-hit != 'true' }}
        name: Generate and build parser
        run: tree-sitter generate --build

      - name: Run tests
        run: tree-sitter test
