name: Tree Sitter Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tree-sitter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure GCC
        run: sudo apt install gcc g++
        shell: bash

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
            node-version: latest
            cache: 'npm'

      - name: Install tree-sitter
        run: npm i tree-sitter-cli

      - name: Generate and build parser
        run: npx tree-sitter generate --build

      - name: Run tests
        run: npx tree-sitter test
