name: Tree Sitter Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tree-sitter-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
            node-version: latest
            cache: 'npm'

      - name: Install tree-sitter
        run: npm i tree-sitter-cli

      - name: Cache parser build
        id: cache-parser-build
        env:
          cache-name: cache-generated-parser
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/mal.so
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('grammar.js') }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ env.cache-name }}-
            ${{ matrix.os }}-build-

      - if: ${{ steps.cache-parser-build.outputs.cache-hit != 'true' }}
        name: Generate and build parser
        run: npx tree-sitter generate --build

      - name: Verify parser up-to-date
        uses: tj-actions/verify-changed-files@v20
        id: verify-updated-parser
        with:
          fail-if-changed: true
          fail-message: Parser is not up-to-date with grammar.
          files: ${{ github.workspace }}/src

      - name: Run tests
        run: npx tree-sitter test
